use super::{ArcanaType, Card, Element, YesOrNo};

/// All 22 Major Arcana cards
pub const MAJOR_ARCANA: &[Card] = &[
    Card {
        name: "The Fool",
        arcana: ArcanaType::Major,
        suit: None,
        number: 0,
        keywords: &["beginnings", "innocence", "spontaneity", "free spirit", "potential"],
        upright: "A new journey begins. You stand at the edge of possibility, ready to step into the unknown with trust and wonder. Embrace the beginner's mind.",
        reversed: "Recklessness or naivety may lead you astray. Consider the consequences before leaping. Fear of the unknown may be holding you back.",
        description: "The Fool is the soul at the start of its journey, untainted by experience and open to all possibilities. With a small pack on their back and a white rose in hand, they step toward the cliff's edge, accompanied only by a loyal dog. This card represents pure potential, the moment before manifestation when all things are possible. The Fool teaches us that every great adventure requires the courage to begin, even when we cannot see where the path may lead.",
        element: Some(Element::Air),
        astrology: Some("Uranus"),
        numerology: Some("0 — the void, pure potential, the egg of creation"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Magician",
        arcana: ArcanaType::Major,
        suit: None,
        number: 1,
        keywords: &["manifestation", "resourcefulness", "power", "inspired action", "creation"],
        upright: "You have all the tools you need to succeed. The elements are at your command—direct your will with focus and intention. Manifestation is within reach.",
        reversed: "Manipulation, illusion, or untapped potential. You may be using your gifts for selfish ends, or failing to recognize your own power. Beware of deception.",
        description: "The Magician stands before a table laden with the tools of the four suits—wand, cup, sword, and pentacle—representing the elements and the resources available to manifest one's desires. With one hand reaching toward the heavens and the other pointing to earth, the Magician channels divine energy into material form. Above his head is the symbol of infinity, suggesting unlimited potential. This card speaks to the power of focused intention and the ability to transform ideas into reality through will and skill.",
        element: Some(Element::Air),
        astrology: Some("Mercury"),
        numerology: Some("1 — initiation, leadership, the spark of creation"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The High Priestess",
        arcana: ArcanaType::Major,
        suit: None,
        number: 2,
        keywords: &["intuition", "mystery", "subconscious", "inner voice", "wisdom"],
        upright: "Trust your intuition. The answers you seek lie within. Pay attention to dreams, symbols, and your inner knowing. Mystery surrounds you—embrace it.",
        reversed: "Secrets may be revealed, or you may be ignoring your intuition. Superficiality blocks deeper understanding. Someone may be withholding information.",
        description: "The High Priestess sits between the pillars of Boaz and Jachin, black and white, representing the duality of existence and the threshold between worlds. Behind her hangs a veil embroidered with pomegranates, obscuring the mysteries beyond. She holds a scroll marked 'TORA', suggesting hidden knowledge. At her feet, the crescent moon speaks to her connection with the unconscious and the feminine mysteries. She invites us to look beyond the surface and trust the wisdom that emerges from stillness and introspection.",
        element: Some(Element::Water),
        astrology: Some("The Moon"),
        numerology: Some("2 — duality, balance, the gateway"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Empress",
        arcana: ArcanaType::Major,
        suit: None,
        number: 3,
        keywords: &["fertility", "nurturing", "abundance", "creativity", "sensuality"],
        upright: "Abundance flows toward you. Nurture your creations and relationships. Connect with nature and your senses. A time of growth and flourishing.",
        reversed: "Creative block or neglect of self-care. Over-dependence on others. Smothering rather than nurturing. Disconnection from the natural world.",
        description: "The Empress sits upon a throne in a verdant landscape, surrounded by wheat fields and a flowing river. She wears a crown of twelve stars, representing the zodiac and her dominion over the cycles of nature. The Venus symbol on her shield speaks to love, beauty, and creativity. A cushion embroidered with a pomegranate hints at fertility and the myth of Persephone. The Empress embodies the divine feminine in her most abundant form—creative, nurturing, and deeply connected to the rhythms of the earth.",
        element: Some(Element::Earth),
        astrology: Some("Venus"),
        numerology: Some("3 — creativity, expression, expansion"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The Emperor",
        arcana: ArcanaType::Major,
        suit: None,
        number: 4,
        keywords: &["authority", "structure", "father figure", "control", "discipline"],
        upright: "Establish order and structure. Take charge of the situation with confidence and clarity. Rules and boundaries serve you now. Leadership is required.",
        reversed: "Tyranny, rigidity, or abuse of power. Lack of discipline or structure. A domineering figure. Inability to adapt or compromise.",
        description: "The Emperor sits upon a stone throne adorned with rams' heads, symbolizing his connection to Aries and the fiery will to rule. In his hand he holds an ankh scepter, representing life and authority, while the other hand grips an orb, signifying his dominion over the material world. Behind him, barren mountains suggest the steadfast, unyielding nature of structure and order. The Emperor represents the divine masculine principle—logic, authority, and the establishment of laws that create stability in chaos. He teaches us that mastery requires discipline.",
        element: Some(Element::Fire),
        astrology: Some("Aries"),
        numerology: Some("4 — stability, foundation, structure"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The Hierophant",
        arcana: ArcanaType::Major,
        suit: None,
        number: 5,
        keywords: &["tradition", "spiritual guidance", "institutions", "conformity", "education"],
        upright: "Seek wisdom from established teachings or mentors. Tradition holds answers. Honor rituals and shared beliefs. A time for learning from the past.",
        reversed: "Rebellion against tradition or breaking free from dogma. Questioning authority. Unconventional paths. Beware of blind conformity.",
        description: "The Hierophant sits on a throne between two pillars, echoing the High Priestess but turned outward toward the world rather than inward toward mystery. He raises two fingers in a gesture of blessing while holding a triple-cross scepter representing the dominion over heaven, earth, and the underworld. Before him kneel two initiates, receiving his wisdom and guidance. This card represents the bridge between the divine and the human, the teacher who transmits sacred knowledge through established channels. The Hierophant speaks to the value of tradition, ritual, and the wisdom passed down through generations.",
        element: Some(Element::Earth),
        astrology: Some("Taurus"),
        numerology: Some("5 — change, challenge, learning through experience"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Lovers",
        arcana: ArcanaType::Major,
        suit: None,
        number: 6,
        keywords: &["love", "harmony", "choices", "values", "alignment"],
        upright: "A meaningful choice presents itself. Follow your heart and values. Union and harmony are possible. Align your actions with what truly matters.",
        reversed: "Disharmony, difficult choices, or misaligned values. Temptation leading astray. Imbalance in relationships. Fear of commitment.",
        description: "The Lovers depicts Adam and Eve in the Garden of Eden, with the Archangel Raphael blessing their union from above. Behind Adam burns the Tree of Knowledge with its forbidden fruit and a serpent coiled among the branches. Behind Eve stands the Tree of Life with twelve fruits representing the zodiac. The mountain between them suggests the challenges that love must overcome. While often associated with romance, this card fundamentally speaks to choice—choosing love, choosing values, choosing alignment between heart and mind. It represents the sacred union of opposites.",
        element: Some(Element::Air),
        astrology: Some("Gemini"),
        numerology: Some("6 — harmony, balance, love, responsibility"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The Chariot",
        arcana: ArcanaType::Major,
        suit: None,
        number: 7,
        keywords: &["determination", "willpower", "victory", "control", "forward motion"],
        upright: "Victory through determination and willpower. Harness opposing forces and direct them toward your goal. Forward momentum—stay focused.",
        reversed: "Lack of direction or control. Aggression without purpose. Inner conflict preventing progress. Force without wisdom.",
        description: "The Chariot depicts a warrior crowned with stars, standing in a chariot drawn by two sphinxes—one black, one white—representing opposing forces that must be mastered and directed. The charioteer wears armor adorned with crescent moons and alchemical symbols, suggesting spiritual protection and transformation. Behind him hangs a canopy of stars, and on his chest is a square representing the material world. The Chariot speaks to the triumph of will over circumstance, the ability to navigate through conflict by maintaining focus and determination. Victory comes to those who master their own contradictions.",
        element: Some(Element::Water),
        astrology: Some("Cancer"),
        numerology: Some("7 — introspection, spiritual seeking, victory"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Strength",
        arcana: ArcanaType::Major,
        suit: None,
        number: 8,
        keywords: &["courage", "compassion", "patience", "inner strength", "influence"],
        upright: "True strength comes from gentleness and patience. Tame your inner beast with compassion. Your inner reserves are greater than you know.",
        reversed: "Weakness, self-doubt, or giving in to base impulses. Force over finesse. Lack of courage. Suppressed anger breaking through.",
        description: "Strength depicts a woman gently closing the jaws of a lion, not through force but through infinite patience and compassion. The infinity symbol above her head connects her to the Magician and suggests spiritual mastery. She wears a white robe signifying purity and a garland of flowers representing nature's bounty. The lion represents our primal instincts and passions—those parts of ourselves that seem untamable. This card teaches that true strength is not domination but integration, not repression but gentle mastery over our own nature.",
        element: Some(Element::Fire),
        astrology: Some("Leo"),
        numerology: Some("8 — power, authority, material accomplishment"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The Hermit",
        arcana: ArcanaType::Major,
        suit: None,
        number: 9,
        keywords: &["solitude", "introspection", "inner guidance", "wisdom", "search for truth"],
        upright: "Withdraw to find your own light. The answers you seek require solitude and reflection. Trust your inner guidance. Wisdom comes from within.",
        reversed: "Isolation, loneliness, or withdrawal from the world. Refusing guidance. Lost in the dark. Excessive solitude.",
        description: "The Hermit stands alone on a mountain peak, holding a lantern that contains a six-pointed star—the Seal of Solomon representing wisdom. Cloaked in grey, he blends with the mountain itself, suggesting that through solitude one becomes one with the heights of spiritual understanding. His staff provides support on the treacherous path. The Hermit has climbed the mountain of experience and now stands apart to contemplate what has been learned. This card speaks to the necessity of periodic withdrawal from the world to reconnect with our inner truth and the wisdom that can only be found in silence.",
        element: Some(Element::Earth),
        astrology: Some("Virgo"),
        numerology: Some("9 — completion, attainment, humanitarian consciousness"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Wheel of Fortune",
        arcana: ArcanaType::Major,
        suit: None,
        number: 10,
        keywords: &["cycles", "change", "destiny", "turning point", "luck"],
        upright: "The wheel turns—change is inevitable. Fortune favors you now. Go with the flow of destiny. A turning point approaches.",
        reversed: "Bad luck, resistance to change, or cycles repeating unlearned lessons. Feeling stuck. External forces working against you.",
        description: "The Wheel of Fortune turns at the center of the card, surrounded by the four fixed signs of the zodiac—Taurus, Leo, Scorpio, and Aquarius—each reading a book of wisdom. The wheel itself contains the letters T-A-R-O and the alchemical symbols for mercury, sulfur, water, and salt. At the corners, the four evangelists watch the eternal cycle. At the top sits the Sphinx, representing wisdom rising above the turning; descending is Anubis, the Egyptian god of the dead; and at the bottom, the serpent Typhon representing destruction. This card teaches that life is cyclical, that fortune rises and falls, and that wisdom lies in accepting change rather than resisting it.",
        element: Some(Element::Fire),
        astrology: Some("Jupiter"),
        numerology: Some("10 — completion, new cycle beginning, divine order"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Justice",
        arcana: ArcanaType::Major,
        suit: None,
        number: 11,
        keywords: &["fairness", "truth", "cause and effect", "law", "accountability"],
        upright: "Truth will prevail. Make decisions with clarity and fairness. You reap what you sow—act with integrity. Balance must be restored.",
        reversed: "Injustice, dishonesty, or unfair treatment. Lack of accountability. Biased decisions. Consequences catching up.",
        description: "Justice sits enthroned between two pillars, holding balanced scales in one hand and an upright sword in the other. The scales represent the objective weighing of evidence and the balance of opposing forces, while the sword signifies the decisive action that must follow judgment. A veil behind her suggests that truth is often obscured and must be revealed. The double-edged sword points upward, indicating that justice serves higher truth. This card speaks to karma, to the law of cause and effect, and to the necessity of making decisions based on truth rather than emotion or bias.",
        element: Some(Element::Air),
        astrology: Some("Libra"),
        numerology: Some("11 — mastery, illumination, spiritual messenger"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Hanged Man",
        arcana: ArcanaType::Major,
        suit: None,
        number: 12,
        keywords: &["surrender", "new perspective", "sacrifice", "waiting", "release"],
        upright: "Surrender to what is. Let go of control and see things from a new angle. Sometimes waiting is the wisest action. Release to receive.",
        reversed: "Resistance, delay, or clinging to control. Useless sacrifice. Stagnation. Martyrdom without purpose.",
        description: "The Hanged Man dangles upside-down from a T-shaped cross made of living wood, suspended by one foot in a posture of surrender. His other leg crosses behind to form a triangle, suggesting transformation. Despite his inverted position, his face is serene, even illuminated—a halo surrounds his head. This is not punishment but voluntary sacrifice, the willing suspension of normal activity to gain new perspective. The Hanged Man teaches that sometimes progress requires stillness, that letting go opens doors that pushing cannot, and that wisdom often comes from seeing the world turned upside down.",
        element: Some(Element::Water),
        astrology: Some("Neptune"),
        numerology: Some("12 — sacrifice, completion of cycle, spiritual growth"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Death",
        arcana: ArcanaType::Major,
        suit: None,
        number: 13,
        keywords: &["transformation", "endings", "transition", "release", "renewal"],
        upright: "A necessary ending brings transformation. Let go of what no longer serves you. Death clears the way for rebirth. Embrace change.",
        reversed: "Resistance to change or fear of endings. Stagnation. Delayed transformation. Clinging to the past prevents growth.",
        description: "Death rides a pale horse across a landscape where kings and commoners alike fall before his power. But look closer—the sun rises between two towers in the distance, promising renewal. A river flows through the scene, suggesting the continuity of life beyond individual forms. At Death's feet, a rose grows from the ground, white petals opening to the sky. This card rarely signifies physical death; rather, it speaks to the transformative power of endings. Death is the great equalizer and the great renewer—what falls must become compost for what rises. Transformation requires the courage to let die what must die.",
        element: Some(Element::Water),
        astrology: Some("Scorpio"),
        numerology: Some("13 — transformation, death and rebirth, sacred power"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Temperance",
        arcana: ArcanaType::Major,
        suit: None,
        number: 14,
        keywords: &["balance", "moderation", "patience", "alchemy", "blending"],
        upright: "Find the middle path. Blend opposing elements into harmony. Patience and moderation bring success. Healing flows through balance.",
        reversed: "Imbalance, excess, or lack of patience. Discord between opposing forces. Haste makes waste. All or nothing thinking.",
        description: "Temperance stands with one foot on land and one in water, pouring liquid between two cups in an endless cycle of blending and transformation. Behind her rises a golden crown, symbolizing the higher consciousness achieved through balance. An iris blooms nearby, representing the rainbow bridge between heaven and earth. The angel's wings suggest spiritual guidance in the art of moderation. Temperance teaches the alchemical art of combining opposites—not diluting them, but creating something new and greater through their union. This is the card of the sacred middle way, of patience, and of the healing that comes from equilibrium.",
        element: Some(Element::Fire),
        astrology: Some("Sagittarius"),
        numerology: Some("14 — temperance, balance, constructive expression"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Devil",
        arcana: ArcanaType::Major,
        suit: None,
        number: 15,
        keywords: &["bondage", "materialism", "shadow self", "temptation", "addiction"],
        upright: "Examine your chains—they may be looser than they appear. Face your shadow. What binds you is often of your own making.",
        reversed: "Breaking free, releasing limiting beliefs, or overcoming addiction. Seeing through illusion. Taking back your power.",
        description: "The Devil sits on a black throne, presiding over two naked figures chained by the neck—but look closely, the chains are loose enough to slip off. The inverted pentagram on his forehead suggests material dominance over spirit, while his torch lights not the way to heaven but illuminates the darkness of our own shadows. The figures bear horns and tails, transformed by their dwelling in the lower realms. This card represents not external evil but our self-imposed bondage—addictions, limiting beliefs, material obsessions, and the parts of ourselves we deny. The Devil teaches that we are prisoners only of our own choosing.",
        element: Some(Element::Earth),
        astrology: Some("Capricorn"),
        numerology: Some("15 — spiritual alchemy, testing, liberation through crisis"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "The Tower",
        arcana: ArcanaType::Major,
        suit: None,
        number: 16,
        keywords: &["sudden change", "upheaval", "revelation", "awakening", "destruction"],
        upright: "Sudden upheaval clears the way for truth. False structures crumble. Though painful, this destruction is necessary for growth. Awakening.",
        reversed: "Avoiding necessary change, delaying the inevitable, or internal crisis. The tower shakes but hasn't fallen—yet. Catastrophe narrowly averted.",
        description: "The Tower is struck by lightning, crown and all, sending two figures tumbling into the abyss. Flames erupt from the windows as the structure collapses. The lightning represents divine truth shattering false foundations, while the falling figures are liberated from their prison even as they fall. This is one of the most feared cards in the deck, yet it brings necessary truth. The Tower represents those moments when external events force us to see reality as it is, not as we wished it to be. Destruction creates space for authentic rebuilding. What rises from these ashes will be built on truth.",
        element: Some(Element::Fire),
        astrology: Some("Mars"),
        numerology: Some("16 — the fall, destruction of ego, new foundation"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "The Star",
        arcana: ArcanaType::Major,
        suit: None,
        number: 17,
        keywords: &["hope", "renewal", "inspiration", "serenity", "spiritual connection"],
        upright: "Hope shines in the darkness. Renewal and inspiration flow to you. Trust in the universe's guidance. Your light is needed.",
        reversed: "Despair, loss of faith, or feeling disconnected from spirit. Hope seems distant. Creative blocks. Disillusionment.",
        description: "The Star follows The Tower, showing a naked woman kneeling by a pool of water, pouring liquid from two vessels—one onto the land, one into the pool. Above her shines a golden star, surrounded by seven smaller stars representing the chakras or classical planets. A bird perches in the tree behind her. The Star is the light that remains when all else has fallen away, the promise of renewal after destruction. She represents hope that is not naive but earned through surviving the darkness. This card speaks to inspiration, spiritual connection, and the serene trust that comes from knowing we are part of something greater.",
        element: Some(Element::Air),
        astrology: Some("Aquarius"),
        numerology: Some("17 — spiritual consciousness, immortality, hope"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The Moon",
        arcana: ArcanaType::Major,
        suit: None,
        number: 18,
        keywords: &["illusion", "fear", "anxiety", "subconscious", "intuition"],
        upright: "Not all is as it seems. Trust your intuition through the fog. Face your fears rather than fleeing them. Dreams carry messages.",
        reversed: "Confusion lifting, secrets revealed, or overcoming fear. The path becomes clear. Deception exposed. Releasing anxiety.",
        description: "The Moon hangs low between two towers, casting an eerie light on a landscape where a dog and wolf howl, and a crayfish emerges from the water. The path winds into the unknown, illuminated only by reflected light. This is the realm of the subconscious, where reality shifts and transforms, where dreams and nightmares dwell. The Moon speaks to the power of illusion and the fears that arise from uncertainty. Yet it also represents deep intuition—the wisdom that emerges when rational sight fails. This card asks us to navigate by feeling rather than seeing, to trust the inner light when the outer world is obscured.",
        element: Some(Element::Water),
        astrology: Some("Pisces"),
        numerology: Some("18 — materialization of soul, spiritual tests"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "The Sun",
        arcana: ArcanaType::Major,
        suit: None,
        number: 19,
        keywords: &["joy", "success", "vitality", "positivity", "consciousness"],
        upright: "Success and joy shine upon you. Vitality and clarity are yours. Be your authentic self without fear. Radiant positivity.",
        reversed: "Temporary depression, lack of clarity, or ego issues. Clouds obscure the sun—temporarily. Overconfidence or burnout.",
        description: "The Sun shines golden and radiant in a clear blue sky, shedding light on a naked child riding a white horse, holding a red banner. Sunflowers tower in the background, turning their faces toward the light. This is the card of pure, unshadowed joy—the consciousness that knows itself completely and expresses itself freely. The child represents the innocence that comes from integration, the white horse purity of spirit, and the banner the victory of light over darkness. The Sun promises success, vitality, and the simple happiness of being truly oneself. After the mystery of the Moon, the Sun brings clarity and warmth.",
        element: Some(Element::Fire),
        astrology: Some("The Sun"),
        numerology: Some("19 — completion, attainment, illumination"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Judgement",
        arcana: ArcanaType::Major,
        suit: None,
        number: 20,
        keywords: &["rebirth", "inner calling", "absolution", "awakening", "redemption"],
        upright: "A call to rise to your higher purpose. The past is absolved—step into your new self. Awakening to your true calling.",
        reversed: "Self-doubt, ignoring the call, or failure to learn from the past. Fear of judgment. Missed opportunities for growth.",
        description: "Judgment shows the archangel Gabriel sounding a trumpet from the heavens, while below, figures rise from coffins, arms outstretched, answering the call to rebirth. The flag on the trumpet bears a cross, representing the intersection of divine and human. Snow-capped mountains in the distance suggest the heights of spiritual attainment. This card speaks not to external judgment but to the inner calling that summons us to our higher selves. It represents the moment of awakening when we hear and respond to our true purpose, when the past is forgiven and a new chapter begins. This is resurrection—not of the body, but of the spirit.",
        element: Some(Element::Fire),
        astrology: Some("Pluto"),
        numerology: Some("20 — spiritual awakening, cosmic consciousness"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "The World",
        arcana: ArcanaType::Major,
        suit: None,
        number: 21,
        keywords: &["completion", "integration", "accomplishment", "wholeness", "fulfillment"],
        upright: "A cycle completes in fulfillment. You have achieved wholeness. Integration of all aspects of self. The world is yours.",
        reversed: "Lack of closure, incomplete projects, or seeking fulfillment externally. Delayed completion. Feeling unfulfilled despite success.",
        description: "The World depicts a dancing figure, wrapped in a purple cloth of spirit, holding wands in both hands to maintain the balance of active and receptive energies. Surrounding the figure is a laurel wreath, symbolizing victory and completion, bound with red ribbons of infinity. In each corner appear the four fixed signs of the zodiac—Taurus, Leo, Scorpio, and Aquarius—representing the integration of all elements and seasons. The dancer moves within the center, at one with the universe. The World represents the end of the Fool's journey and the beginning of a new one. It speaks to completion not as ending but as fulfillment, the achievement of integration and the realization that we contain the entire universe within us.",
        element: Some(Element::Earth),
        astrology: Some("Saturn"),
        numerology: Some("21 — cosmic consciousness, mastery, fulfillment"),
        yes_or_no: YesOrNo::Yes,
    },
];

/// Get a Major Arcana card by number (0-21)
#[allow(dead_code)]
pub fn get_by_number(number: u8) -> Option<&'static Card> {
    MAJOR_ARCANA.iter().find(|c| c.number == number)
}

/// Get a Major Arcana card by name (case-insensitive)
#[allow(dead_code)]
pub fn get_by_name(name: &str) -> Option<&'static Card> {
    let name_lower = name.to_lowercase();
    MAJOR_ARCANA
        .iter()
        .find(|c| c.name.to_lowercase() == name_lower)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_major_arcana_count() {
        assert_eq!(MAJOR_ARCANA.len(), 22);
    }

    #[test]
    fn test_get_by_number() {
        assert_eq!(get_by_number(0).unwrap().name, "The Fool");
        assert_eq!(get_by_number(21).unwrap().name, "The World");
        assert!(get_by_number(22).is_none());
    }

    #[test]
    fn test_get_by_name() {
        assert_eq!(get_by_name("The Fool").unwrap().number, 0);
        assert_eq!(get_by_name("the fool").unwrap().number, 0);
        assert_eq!(get_by_name("THE TOWER").unwrap().number, 16);
        assert!(get_by_name("Not a Card").is_none());
    }
}
