use super::{ArcanaType, Card, Suit, YesOrNo};

/// All 56 Minor Arcana cards (14 cards in each of 4 suits)
pub const MINOR_ARCANA: &[Card] = &[
    // ===== WANDS (Fire) =====
    Card {
        name: "Ace of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 1,
        keywords: &["inspiration", "creation", "desire", "potential", "spark"],
        upright: "A spark of creative energy emerges. New inspiration strikes like lightning. The seed of passion is planted—nurture it into flame.",
        reversed: "Lack of motivation, creative block, or delayed inspiration. Missed opportunities. Energy scattered rather than focused.",
        description: "The Ace of Wands shows a hand emerging from a cloud, offering a sprouting wand that bursts with leaves and shoots of new growth. This is the pure potential of fire—creative inspiration, passion, and the spark of a new venture. Like all Aces, it represents a gift from the universe, an opportunity that requires action to manifest. The castle in the distance suggests the rewards that await those who follow this creative impulse.",
        element: None, // Uses suit's element
        astrology: Some("Aries, Leo, Sagittarius"),
        numerology: Some("1 — new beginning, creative spark"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Two of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 2,
        keywords: &["planning", "decisions", "discovery", "partnership", "future"],
        upright: "You stand at a crossroads, world in hand. Plan your next move carefully. A partnership may help expand your horizons. Look beyond familiar territory.",
        reversed: "Fear of the unknown, poor planning, or playing it too safe. Indecision prevents progress. Partnership difficulties.",
        description: "A figure stands on a castle balcony, holding a globe in one hand and a wand in the other, gazing out over a vast landscape toward distant mountains. A second wand is fixed to the railing behind them. This is the card of planning and preparation—the moment between having an idea (Ace) and taking action (Three). The world is literally in your hands, but you must choose which path to take. It speaks to the expansion of vision beyond current circumstances.",
        element: None,
        astrology: Some("Mars in Aries"),
        numerology: Some("2 — duality, choice, planning"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Three of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 3,
        keywords: &["expansion", "foresight", "leadership", "progress", "exploration"],
        upright: "Your ships are coming in. Expansion and growth await those who have planned well. Leadership brings success. Look to the horizon.",
        reversed: "Delays, obstacles to expansion, or failed ventures. Lack of foresight. Projects stall. Overextension.",
        description: "A figure stands on a cliff overlooking the sea, watching three ships sail toward distant shores. The wands that were planted in the Two have now grown and bear fruit. This card represents the first results of your plans and the expansion of your enterprise beyond its origins. It speaks to leadership, foresight, and the courage to explore new territories. Success is visible on the horizon, but it requires continued vision and effort to fully manifest.",
        element: None,
        astrology: Some("Sun in Aries"),
        numerology: Some("3 — creativity, expansion, first results"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Four of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 4,
        keywords: &["celebration", "harmony", "marriage", "community", "achievement"],
        upright: "A time of celebration and joy. Harvest your achievements with loved ones. Harmony in community. A milestone reached—enjoy it.",
        reversed: "Lack of support, cancelled celebrations, or disharmony. Superficial connections. Feeling excluded from community.",
        description: "Two figures dance beneath a garland of flowers suspended between four wands, celebrating in front of a castle. This is the card of joyful celebration—the harvest festival, the wedding, the completion of a significant phase. It represents the harmony that comes when individual efforts are woven into community. The castle suggests the stability that has been achieved. This card invites you to pause and celebrate how far you've come before beginning the next cycle.",
        element: None,
        astrology: Some("Venus in Aries"),
        numerology: Some("4 — stability, foundation, celebration"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Five of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 5,
        keywords: &["conflict", "competition", "tension", "diversity", "struggle"],
        upright: "Healthy competition stimulates growth. Diverse energies clash but create dynamism. Conflict may be necessary for progress. Stand your ground.",
        reversed: "Avoiding conflict, resolution of disputes, or destructive competition. End of struggle. Finding common ground.",
        description: "Five figures brandish wands in what appears to be chaotic conflict, yet no one seems to be injured. This card represents the clash of competing interests, ideas, or energies. While it can indicate genuine conflict, it often suggests healthy competition or the creative tension that arises when different perspectives meet. The energy is dynamic and active—sometimes necessary to clear the air or test ideas. It asks whether the conflict serves growth or merely drains energy.",
        element: None,
        astrology: Some("Saturn in Leo"),
        numerology: Some("5 — challenge, change, conflict"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Six of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 6,
        keywords: &["victory", "recognition", "success", "pride", "public acclaim"],
        upright: "Victory and recognition are yours. Others acknowledge your achievements. Success after effort. Public acclaim or promotion.",
        reversed: "Delayed recognition, excessive pride, or fear of success. Victory feels hollow. Lack of acknowledgment. Fall from grace.",
        description: "A victorious rider on horseback is greeted with cheers, carrying a wand crowned with a laurel wreath. The six wands represent triumph after the challenges of the five. This card speaks to public recognition, the acknowledgment of your efforts by others, and the confidence that comes from proven success. Yet it also carries a warning against hubris—true victory includes gratitude for those who supported the journey. The card celebrates achievement while reminding us that recognition is sweetest when shared.",
        element: None,
        astrology: Some("Jupiter in Leo"),
        numerology: Some("6 — harmony, success, recognition"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Seven of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 7,
        keywords: &["defense", "perseverance", "courage", "standing firm", "challenge"],
        upright: "Stand your ground against opposition. Courage in the face of challenge. Defend your position with conviction. Perseverance wins.",
        reversed: "Overwhelmed by opposition, giving up too easily, or unnecessary defensiveness. Exhaustion from constant struggle. Knowing when to yield.",
        description: "A figure stands on higher ground, defending their position against six wands raised against them from below. This is the card of standing firm in your convictions, of having the courage to hold your ground when challenged. The higher position suggests an advantage, but the battle is still real. It speaks to the need for perseverance when success attracts competition or jealousy. The card asks whether your defense serves your highest good or whether you're fighting battles not worth winning.",
        element: None,
        astrology: Some("Mars in Leo"),
        numerology: Some("7 — spiritual test, perseverance, defense"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Eight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 8,
        keywords: &["speed", "action", "movement", "swift progress", "communication"],
        upright: "Rapid movement and swift progress. Messages arrive quickly. Action is required—strike while the iron is hot. Momentum carries you forward.",
        reversed: "Delays, obstacles to progress, or rushed action. Messages blocked. Impatience creates errors. Slow down to go faster.",
        description: "Eight wands fly through the air like arrows, descending rapidly toward their target. This is the card of swift action and rapid communication—all the preparation and planning now manifest in sudden movement. There is no time for hesitation; events are unfolding quickly and require decisive response. The landscape below suggests that action happens within a context, but the emphasis is on speed and direction. This card brings urgency and the excitement of rapid progress.",
        element: None,
        astrology: Some("Mercury in Sagittarius"),
        numerology: Some("8 — power, movement, swift action"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Nine of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 9,
        keywords: &["resilience", "last stand", "courage", "persistence", "boundaries"],
        upright: "You've been through battles and stand watchful. Resilience in the face of exhaustion. One last challenge to face. Stand guard but rest when you can.",
        reversed: "Exhaustion, giving up, or paranoia. Defensiveness that blocks help. Burnout from constant vigilance. Need for true rest.",
        description: "A battle-worn figure stands leaning on a wand, watching for threats, with eight other wands standing like a fence behind them. This is the card of the wounded warrior, standing guard after the battle is supposedly won. It speaks to resilience, to the courage to continue when exhausted, and to the wisdom of boundaries. The figure has survived and learned—note the bandaged head—but remains vigilant. This card acknowledges the cost of perseverance while affirming its necessity.",
        element: None,
        astrology: Some("Moon in Sagittarius"),
        numerology: Some("9 — completion, resilience, final test"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Ten of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 10,
        keywords: &["burden", "responsibility", "overload", "hard work", "completion"],
        upright: "The weight of responsibility grows heavy. You're carrying too much alone. Delegate what you can. The end of a cycle is near—persevere.",
        reversed: "Release of burden, delegation, or collapse under pressure. Refusing unnecessary responsibility. Finding a better way.",
        description: "A figure struggles under the weight of ten wands, bent over as they carry their burden toward a distant village. This card represents the culmination of the wands energy—the point where enthusiasm and creative fire become obligation and burden. The figure can see their destination but cannot enjoy the journey under such weight. It speaks to the necessity of examining what we carry and asking whether each responsibility serves our goals. Sometimes completion requires not more effort but the wisdom to set down what no longer serves.",
        element: None,
        astrology: Some("Saturn in Sagittarius"),
        numerology: Some("10 — completion, burden, transition"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Page of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 11,
        keywords: &["enthusiasm", "exploration", "discovery", "freedom", "new ideas"],
        upright: "A messenger brings exciting news or ideas. New enthusiasm for a venture. Explore with an open mind. Creative potential stirs.",
        reversed: "Bad news, lack of direction, or impulsive behavior. Ideas without follow-through. Missed messages. Restlessness without purpose.",
        description: "A young figure stands in a barren landscape, holding a wand and gazing at it with curiosity, as if discovering its power for the first time. The salamanders on their tunic suggest connection to fire elementals. This is the explorer, the bringer of news, the one who approaches life with enthusiasm and openness. The Page of Wands represents new ideas, creative inspiration, and the courage to explore unknown territory. There is an innocence here—the enthusiasm of one who has not yet learned the obstacles ahead.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Knight of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 12,
        keywords: &["action", "adventure", "passion", "impulsiveness", "energy"],
        upright: "Charge forward with passion and courage. Adventure calls—answer it. Swift, decisive action. Energy and enthusiasm carry you.",
        reversed: "Recklessness, impulsiveness, or rushing without thought. Anger or aggression. Delayed action. Burnout from excessive haste.",
        description: "A knight in armor rides a rearing horse, holding a wand and charging forward with fierce determination. The plumes on their helmet and the horse's mane stream behind them, suggesting rapid movement. This is the most action-oriented of the knights—the one who acts first and thinks later. The card brings energy, passion, and the courage to pursue goals with single-minded focus. Yet it also warns of impulsiveness and the dangers of charging ahead without considering the terrain. The Knight of Wands is magnificent in motion but may miss important details.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Queen of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 13,
        keywords: &["confidence", "warmth", "determination", "charisma", "creativity"],
        upright: "Lead with warmth and confidence. Your charisma draws others to your vision. Creative energy flows through you. Trust your instincts.",
        reversed: "Self-doubt, jealousy, or demanding attention. Creative blocks. Overbearing behavior. Insecurity masked as confidence.",
        description: "The Queen of Wands sits on a throne adorned with lions and sunflowers, holding a wand in one hand and a sunflower in the other. A black cat sits at her feet, suggesting mystery and intuition alongside her obvious confidence. This queen combines the fire of wands with mature mastery—she is warm, charismatic, and deeply creative. She trusts her instincts and leads others through the power of her vision. The cat reminds us that her confidence is grounded in deep intuitive wisdom, not merely surface charm.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "King of Wands",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Wands),
        number: 14,
        keywords: &["leadership", "vision", "entrepreneur", "charisma", "mastery"],
        upright: "Lead with vision and passion. Entrepreneurial spirit brings success. Take bold action toward your goals. Inspire others to follow.",
        reversed: "Tyranny, impulsiveness, or ruthless ambition. Leadership without wisdom. Burning bridges. Force over inspiration.",
        description: "The King of Wands sits on his throne, holding a flowering wand and gazing toward the future with confident vision. The salamanders on his cloak and throne suggest his mastery over fire elementals. This is the visionary leader, the entrepreneur, the one who sees possibilities others miss and has the charisma to inspire others to join the quest. He combines the passion of wands with the wisdom of mastery, directing creative energy toward concrete achievement. His gaze is fixed on the horizon—he leads not by looking back but by pointing the way forward.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    // ===== CUPS (Water) =====
    Card {
        name: "Ace of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 1,
        keywords: &["love", "emotions", "intuition", "spirituality", "new feelings"],
        upright: "Love overflows from an open heart. New emotional beginnings. Spiritual connection and intuition awaken. The cup of joy is offered.",
        reversed: "Emotional block, empty cup, or repressed feelings. Missed opportunity for love. Spiritual disconnection. Emotional exhaustion.",
        description: "A hand emerges from a cloud offering a cup overflowing with five streams of water, representing the five senses and the abundance of emotion. Above the cup flies a dove carrying a host, symbolizing the descent of spirit into matter. This is the pure potential of water—love, emotion, intuition, and spiritual connection. Like all Aces, it represents a gift, an opportunity for emotional fulfillment that requires openness to receive. The lotuses blooming below suggest the beauty that emerges when we accept this offering.",
        element: None,
        astrology: Some("Cancer, Scorpio, Pisces"),
        numerology: Some("1 — new emotional beginning"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Two of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 2,
        keywords: &["partnership", "union", "harmony", "attraction", "connection"],
        upright: "A meaningful partnership forms. Mutual attraction and harmony. Union of hearts and minds. Balance in relationship.",
        reversed: "Imbalance in partnership, broken union, or disharmony. One-sided attraction. Misalignment of values. Separation.",
        description: "Two figures exchange cups in a gesture of mutual giving, beneath the winged lion of St. Mark inscribed with a caduceus. This is the card of true partnership—the meeting of equals in love, friendship, or business. The lion with wings suggests that such unions have the power to elevate us beyond our individual limitations. It represents the harmony that comes when two beings recognize each other as kindred spirits. This is not merely romance but the sacred meeting of souls.",
        element: None,
        astrology: Some("Venus in Cancer"),
        numerology: Some("2 — duality, partnership, choice"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Three of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 3,
        keywords: &["celebration", "friendship", "joy", "community", "abundance"],
        upright: "Celebrate with friends and community. Joy multiplies when shared. Creative collaboration succeeds. Emotional abundance flows.",
        reversed: "Overindulgence, gossip, or exclusion from community. Superficial friendships. Celebrations feel empty. Isolation.",
        description: "Three women raise their cups in celebration, dancing together in a garden of abundance. This is the card of communal joy—the celebration that is richer for being shared. It represents friendship, creative collaboration, and the emotional fulfillment that comes from belonging. The fruits and pumpkins at the women's feet suggest the harvest of emotional and creative labor. This card invites you to gather your tribe and celebrate the abundance that flows through connection.",
        element: None,
        astrology: Some("Mercury in Cancer"),
        numerology: Some("3 — creativity, expression, celebration"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Four of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 4,
        keywords: &["contemplation", "apathy", "re-evaluation", "missed opportunity", "meditation"],
        upright: "A time for introspection and re-evaluation. Restlessness with the status quo. New possibilities offered—will you see them? Contemplate before choosing.",
        reversed: "Boredom, missed opportunities, or disconnection from emotions. Taking things for granted. Refusing to see what's offered. Stagnation.",
        description: "A figure sits beneath a tree, contemplating three cups before them while a hand offers a fourth cup from a cloud—unseen and unacknowledged. This is the card of emotional stagnation, of being so focused on what we don't have that we miss what is offered. Yet it also represents necessary contemplation, the period of dissatisfaction that precedes growth. The meditation is valid, but beware of apathy that blinds you to new possibilities. Sometimes discontent is the soul's way of preparing for change.",
        element: None,
        astrology: Some("Moon in Cancer"),
        numerology: Some("4 — stability, rest, contemplation"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Five of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 5,
        keywords: &["loss", "grief", "disappointment", "regret", "acceptance"],
        upright: "Grief is real and must be felt. Three cups have spilled, but two remain. Turn from what was lost to what remains. Healing comes through acceptance.",
        reversed: "Moving on from grief, acceptance of loss, or finding hope. Recovery from disappointment. New perspective on past pain.",
        description: "A cloaked figure stands before three spilled cups, head bowed in grief, unaware of two upright cups behind them. This is the card of loss and the grief that follows—yet it also contains the seed of healing. The spilled cups cannot be unspilled; grief must be honored. But the figure's focus on loss blinds them to what remains. The bridge in the background suggests the way forward, but it requires turning away from the spilled cups. This card acknowledges pain while reminding us that loss is never the whole story.",
        element: None,
        astrology: Some("Mars in Scorpio"),
        numerology: Some("5 — change, loss, challenge"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Six of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 6,
        keywords: &["nostalgia", "innocence", "childhood", "memories", "gift"],
        upright: "Sweet memories bring comfort. A gift from the past or a reunion. Innocence and simple pleasures. Childhood connections resurface.",
        reversed: "Stuck in the past, childishness, or rose-colored memories. Refusing to grow up. Unhealthy nostalgia blocks present joy.",
        description: "Two children exchange cups filled with flowers in a garden of nostalgic beauty. This is the card of memory and innocence, of the sweetness that comes from looking back at simpler times. It can indicate reunion with someone from the past, gifts given or received in love, or the healing power of childlike wonder. Yet it also warns against being trapped by nostalgia, of preferring the remembered past to the living present. The flowers in the cups suggest that memory, like flowers, is beautiful but ephemeral.",
        element: None,
        astrology: Some("Sun in Scorpio"),
        numerology: Some("6 — harmony, nostalgia, innocence"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Seven of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 7,
        keywords: &["choices", "fantasy", "wishful thinking", "illusion", "imagination"],
        upright: "Many possibilities present themselves. Dreams and visions abound. Beware of illusions—discern what is real. Choose wisely from your options.",
        reversed: "Reality check, clearing illusions, or making a decision. Seeing through fantasy. Taking practical action. Clarity emerges.",
        description: "Seven cups float in a cloud, each containing a different vision—a snake, a castle, jewels, a laurel wreath, a dragon, a mask, and a figure veiled in white. This is the card of choices and illusions, of the imagination unbounded by reality. The visions are seductive but not all are what they appear. This card asks you to distinguish between genuine possibility and mere fantasy, between what will nourish and what will deceive. The abundance of choice can be paralyzing—clarity comes from knowing your true desires.",
        element: None,
        astrology: Some("Venus in Scorpio"),
        numerology: Some("7 — choices, imagination, discernment"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Eight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 8,
        keywords: &["departure", "seeking more", "abandonment", "journey", "growth"],
        upright: "Leave behind what no longer fulfills you. Seek deeper meaning elsewhere. Courage to walk away. A necessary journey toward authenticity.",
        reversed: "Fear of leaving, stagnation, or returning to the familiar. Difficulty letting go. Unfinished business. Avoidance of growth.",
        description: "A figure walks away from eight stacked cups, leaving behind emotional investments to seek something more meaningful on a difficult path through mountains. This is the card of necessary departure, of the courage to leave behind what is comfortable but no longer sufficient. The cups were not spilled or stolen—they were simply outgrown. This card speaks to the journey toward authenticity, the willingness to abandon security in pursuit of deeper fulfillment. It is a card of both sadness and hope, of mourning what was while moving toward what might be.",
        element: None,
        astrology: Some("Saturn in Pisces"),
        numerology: Some("8 — transition, seeking, departure"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Nine of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 9,
        keywords: &["satisfaction", "contentment", "wish fulfillment", "gratitude", "happiness"],
        upright: "Emotional fulfillment and contentment. Wishes come true. Gratitude for abundance. The 'wish card'—satisfaction achieved.",
        reversed: "Dissatisfaction despite having enough, or wishes unfulfilled. Taking blessings for granted. False contentment masking deeper needs.",
        description: "A satisfied figure sits before nine arranged cups, arms crossed in contentment. This is often called the 'wish card'—the card of emotional fulfillment and satisfaction. The cups are arranged in an arc of achievement, suggesting that wishes have been granted and contentment achieved. Yet the figure's posture is somewhat closed, suggesting that satisfaction can become complacency. This card celebrates fulfillment while asking whether true happiness comes from having what we want or from wanting what we have.",
        element: None,
        astrology: Some("Jupiter in Pisces"),
        numerology: Some("9 — fulfillment, satisfaction, wishes"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Ten of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 10,
        keywords: &["harmony", "family", "joy", "alignment", "emotional abundance"],
        upright: "Complete emotional fulfillment. Harmony in family and relationships. True alignment of heart and spirit. Joy that overflows.",
        reversed: "Broken harmony, family discord, or misalignment. False happiness. Disconnection from loved ones. Empty idealism.",
        description: "Two arms raise in blessing beneath a rainbow arcing over ten cups, while a happy family celebrates in the foreground. This is the card of complete emotional fulfillment—the harmony of family, community, and spirit aligned. The rainbow represents the divine promise, the connection between heaven and earth through love. This card speaks to the abundance that comes from healthy relationships and emotional authenticity. It is the culmination of the cups journey—the realization that true wealth lies in connection and love.",
        element: None,
        astrology: Some("Mars in Pisces"),
        numerology: Some("10 — completion, harmony, fulfillment"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Page of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 11,
        keywords: &["messenger", "creative beginnings", "intuition", "sensitivity", "imagination"],
        upright: "A message of love or creativity arrives. New emotional beginnings. Trust your intuition. Creative inspiration flows like water.",
        reversed: "Emotional immaturity, creative blocks, or disappointing news. Over-sensitivity. Misinterpretation of feelings. Emotional withdrawal.",
        description: "A young figure stands by the sea, holding a cup from which a fish emerges—an unexpected gift from the unconscious. The Page of Cups is the dreamer, the artist, the one who brings messages of love and creative inspiration. There is a innocence here, a willingness to be surprised by emotion and intuition. The fish suggests that the unconscious has messages to deliver if we are open to receiving them. This page brings news that touches the heart and awakens the imagination.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Knight of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 12,
        keywords: &["romance", "charm", "imagination", "idealism", "proposal"],
        upright: "A romantic offer or proposition arrives. Follow your heart with courage. Charm and idealism guide you. Pursue your dreams.",
        reversed: "Unrealistic ideals, emotional manipulation, or disappointment in love. Proposals without follow-through. Moodiness. Illusion over reality.",
        description: "A knight in armor rides forward holding a cup, as if offering it to someone unseen. This is the romantic, the dreamer in action, pursuing the ideal with devotion. The Knight of Cups follows his heart wherever it leads, bringing offers of love, creative collaboration, or spiritual pursuit. Yet there is a warning here too—the knight's gaze is fixed on the cup, not on the path ahead. Idealism is beautiful but can lead into difficulty if not balanced with practical awareness.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Queen of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 13,
        keywords: &["compassion", "intuition", "emotional depth", "nurturing", "empathy"],
        upright: "Trust your deep intuition. Compassion and empathy guide you. Emotional maturity brings wisdom. Nurture yourself and others.",
        reversed: "Emotional overwhelm, dependency, or blocked intuition. Over-sensitivity becomes paralysis. Martyrdom. Loss of emotional boundaries.",
        description: "The Queen of Cups sits on a throne by the water, holding an ornate cup, gazing into it with an expression of deep contemplation. Her throne is decorated with mermaids and fish, suggesting her mastery of the watery realm of emotion and intuition. This queen embodies compassion, empathy, and deep emotional wisdom. She feels profoundly but is not overwhelmed—her intuition is a tool she has learned to use. The sealed cup on her throne suggests that some mysteries remain hidden even to her, and she is at peace with this.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "King of Cups",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Cups),
        number: 14,
        keywords: &["emotional balance", "compassion", "diplomacy", "mastery", "calm"],
        upright: "Emotional mastery brings calm authority. Lead with compassion and wisdom. Diplomacy resolves conflicts. Balance heart and mind.",
        reversed: "Emotional manipulation, volatility, or repressed feelings. Unstable moods. Using emotions to control others. Inner turmoil masked.",
        description: "The King of Cups sits on his throne upon the water, holding a cup in one hand and a scepter in the other, looking out with calm authority. His throne is decorated with fish and ships, suggesting his command of the emotional realm. Unlike the Knight who is lost in emotion or the Page who is discovering it, the King has mastered his feelings without repressing them. He represents emotional maturity—the ability to feel deeply while remaining balanced, to lead with compassion while maintaining boundaries. The ship suggests that he can navigate any emotional waters.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    // ===== SWORDS (Air) =====
    Card {
        name: "Ace of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 1,
        keywords: &["clarity", "breakthrough", "new idea", "truth", "mental clarity"],
        upright: "Mental breakthrough and clarity. A new idea cuts through confusion. Truth is revealed. Use this clarity wisely.",
        reversed: "Confusion, chaos, or false clarity. Misunderstanding. Misuse of intellect. Truth obscured. Mental blocks.",
        description: "A hand emerges from a cloud offering an upright sword, its point piercing a crown adorned with a wreath. This is the pure potential of air—intellect, clarity, truth, and the power of the mind. Like all Aces, it represents a gift: the ability to see clearly, to cut through illusion, to have a breakthrough insight. The double-edged sword reminds us that truth cuts both ways and must be wielded with care. This is the flash of inspiration, the moment when confusion gives way to understanding.",
        element: None,
        astrology: Some("Gemini, Libra, Aquarius"),
        numerology: Some("1 — new idea, mental breakthrough"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Two of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 2,
        keywords: &["indecision", "stalemate", "blocked emotions", "avoidance", "choice"],
        upright: "A difficult choice requires decision. Information is incomplete—trust your intuition. Remove the blindfold and see clearly. Balance opposing views.",
        reversed: "Indecision, confusion, or avoidance of truth. Information overload paralyzes choice. Emotional release brings clarity. No decision is also a choice.",
        description: "A blindfolded figure sits holding two crossed swords, back to the water, moon above. This is the card of difficult decisions and stalemate. The blindfold suggests that the answer cannot be found through ordinary sight—it requires inner vision or acceptance of uncertainty. The crossed swords represent opposing options that seem equally valid. The water behind suggests that emotions are being blocked or ignored. This card acknowledges that sometimes we must choose without perfect information, that indecision is itself a decision with consequences.",
        element: None,
        astrology: Some("Moon in Libra"),
        numerology: Some("2 — duality, choice, stalemate"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Three of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 3,
        keywords: &["heartbreak", "grief", "sorrow", "rejection", "emotional pain"],
        upright: "Heartbreak and sorrow must be acknowledged. Pain is real but temporary. Grieve what is lost. The storm will pass.",
        reversed: "Recovery from heartbreak, releasing pain, or forgiveness. Healing begins. Overcoming sorrow. Moving forward with wisdom.",
        description: "Three swords pierce a heart against a backdrop of storm clouds and rain. This is the card of heartbreak, grief, and emotional pain—one of the most challenging cards in the deck. Yet it also represents the clarity that comes through pain, the understanding that only sorrow can bring. The swords are not random violence but precise wounds—the pain of truth, of loss, of betrayal acknowledged. This card does not deny pain but validates it, reminding us that grief is part of the human experience and that healing begins with acknowledgment.",
        element: None,
        astrology: Some("Saturn in Libra"),
        numerology: Some("3 — sorrow, necessary pain, growth through grief"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Four of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 4,
        keywords: &["rest", "recovery", "meditation", "contemplation", "peace"],
        upright: "Rest and recover. Retreat for contemplation and healing. Peace is found in stillness. Gather strength for what comes next.",
        reversed: "Restlessness, burnout, or refusal to rest. Recovery delayed. Isolation becomes loneliness. Time to re-engage.",
        description: "A knight lies in repose within a church, three swords above and one beneath, stained glass showing a figure in prayer. This is the card of necessary rest, the pause between battles, the retreat for healing. After the pain of the Three, the Four offers respite. The swords suggest that the challenges remain, but for now, they are set aside. This card speaks to the wisdom of retreat, of allowing the mind and heart to recover before facing what comes next. The stained glass suggests that this rest is sacred, necessary for the soul as much as the body.",
        element: None,
        astrology: Some("Jupiter in Libra"),
        numerology: Some("4 — rest, stability, recovery"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Five of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 5,
        keywords: &["conflict", "defeat", "winning at costs", "betrayal", "hollow victory"],
        upright: "Victory comes at a cost. Consider what you sacrifice to win. Conflict leaves wounds on all sides. Know when to walk away.",
        reversed: "Reconciliation, making amends, or accepting defeat gracefully. Resolving conflict. Learning from past battles. Openness to peace.",
        description: "A figure gathers swords while two others walk away in defeat, clouds gathering overhead. This is the card of conflict and its aftermath—particularly the hollow victory where winning costs more than it gains. The central figure has the swords but has lost the relationships, suggesting that some battles are not worth winning. This card asks us to examine our approach to conflict: Are we fighting for something worth having? What do we lose when we insist on being right? Sometimes the wisest choice is to lay down the sword.",
        element: None,
        astrology: Some("Venus in Aquarius"),
        numerology: Some("5 — conflict, loss, challenge"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Six of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 6,
        keywords: &["transition", "moving on", "journey", "leaving behind", "change"],
        upright: "Move toward calmer waters. Transition to a better place. Leave behind what troubles you. Healing comes through change.",
        reversed: "Resistance to change, stagnation, or inability to move on. Troubled waters persist. Delayed transition. Carrying baggage forward.",
        description: "A boatman ferries a figure and child across water, six swords standing upright in the boat, moving from choppy to calm waters. This is the card of transition and passage—the journey from difficulty toward peace. The swords represent the mental baggage we carry even as we seek better circumstances. The card acknowledges that transitions are necessary but not always easy; we bring our thoughts and memories with us even as we move toward healing. The child suggests that new beginnings are possible, that we can carry hope even through difficult passages.",
        element: None,
        astrology: Some("Mercury in Aquarius"),
        numerology: Some("6 — harmony, transition, healing"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Seven of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 7,
        keywords: &["deception", "strategy", "stealth", "betrayal", "getting away with something"],
        upright: "Strategy and cunning may be required. Be aware of deception—yours or others'. Not everything is as it seems. Choose your battles.",
        reversed: "Coming clean, confession, or exposure of deceit. Strategy fails. Consequences arrive. Honesty becomes the better policy.",
        description: "A figure sneaks away from a camp carrying five swords, looking back at two left behind. This is the card of deception, strategy, and the gray areas of ethics. The figure is stealing but also choosing—taking what seems valuable while leaving the rest. This card can indicate the need for clever strategy, but it also warns of the cost of deceit. Are you being deceived, or are you the deceiver? Is this wise caution or unethical behavior? The card does not judge but asks us to consider the consequences of our tactics.",
        element: None,
        astrology: Some("Moon in Aquarius"),
        numerology: Some("7 — strategy, deception, testing"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Eight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 8,
        keywords: &["restriction", "imprisonment", "victim mentality", "negative thoughts", "feeling trapped"],
        upright: "You feel trapped but the bindings are loose. Negative thoughts create prison bars. Free yourself by changing perspective. The way out exists.",
        reversed: "Release, taking control, or seeing options clearly. Freedom from self-imposed limits. New perspective liberates. Breaking free.",
        description: "A blindfolded figure stands surrounded by eight swords, seemingly trapped, yet the bindings are loose and a path lies open. This is the card of self-imposed limitation, of the prison we create in our own minds. The figure is blindfolded—they cannot see the way out—but the swords form a cage that exists more in perception than reality. This card speaks to the power of negative thinking, of how our beliefs about our limitations can become more binding than any external constraint. The message is clear: the prison is imaginary, and freedom awaits those who remove the blindfold.",
        element: None,
        astrology: Some("Jupiter in Gemini"),
        numerology: Some("8 — restriction, mental blocks, self-imposed limits"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Nine of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 9,
        keywords: &["anxiety", "worry", "fear", "nightmares", "negative thinking"],
        upright: "Anxiety and worry weigh heavily. Nightmares reflect inner fears. Seek help—do not suffer alone. This too shall pass.",
        reversed: "Hope emerging, releasing anxiety, or seeking support. Recovery from depression. Facing fears. Finding light in darkness.",
        description: "A figure sits up in bed, head in hands, nine swords hanging on the wall behind them, representing the weight of anxiety and negative thought. This is the card of worry, insomnia, and the mental anguish that keeps us awake at night. The swords are not attacking—the figure is alone with their own thoughts. This card acknowledges the reality of anxiety and depression while reminding us that these states, however overwhelming, are temporary. The first step toward healing is reaching out, sharing the burden, and remembering that morning always comes.",
        element: None,
        astrology: Some("Mars in Gemini"),
        numerology: Some("9 — worry, anxiety, mental anguish"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Ten of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 10,
        keywords: &["painful ending", "deep wounds", "betrayal", "crisis", "rock bottom"],
        upright: "A painful ending arrives. Rock bottom provides foundation for rebirth. The worst is over. Dawn follows this dark night.",
        reversed: "Recovery, resurrection, or resisting inevitable endings. Unable to let go. Things get worse before better. Surviving crisis.",
        description: "A figure lies face down with ten swords in their back, yet the sky above shows the dawn breaking. This is the card of painful endings, of betrayal and crisis that feels like death. Yet it also represents the certainty that the worst has passed—there are no more swords to fall. The dawn promises that even after the darkest night, light returns. This card does not deny the pain of endings but affirms that they are necessary for new beginnings. Sometimes we must be completely brought down to rise again.",
        element: None,
        astrology: Some("Sun in Gemini"),
        numerology: Some("10 — painful ending, crisis, necessary completion"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Page of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 11,
        keywords: &["curiosity", "communication", "new ideas", "vigilance", "mental energy"],
        upright: "A message brings new information. Curiosity leads to discovery. Mental energy is high. Stay alert and observant.",
        reversed: "Deception, gossip, or hasty communication. Spreading rumors. Speaking without thinking. Missed messages. Mental scatteredness.",
        description: "A young figure stands with sword raised, looking alertly into the distance, wind blowing through the trees. This is the scout, the bringer of news, the one who observes and reports. The Page of Swords represents curiosity, mental alertness, and the enthusiasm of new ideas. There is a quickness here, a readiness to learn and communicate, but also a potential for haste and superficiality. The page brings information that requires attention—stay vigilant and think before speaking.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Knight of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 12,
        keywords: &["action", "impulsiveness", "defense", "intellect", "haste"],
        upright: "Swift action is required. Charge forward with intellect and courage. Cut through obstacles. Be decisive but not reckless.",
        reversed: "Recklessness, rushing into danger, or thoughtless action. Aggression without cause. Arguments and conflict. Impulsive mistakes.",
        description: "A knight charges forward on horseback, sword raised, armor gleaming, storm winds behind them. This is the most swift and decisive of the knights—the one who acts immediately upon thought. The Knight of Swords brings energy, decisiveness, and the courage to cut through obstacles. Yet the storm clouds suggest that this haste may be reckless, that charging forward without full information carries risk. This card brings necessary action but warns against acting without thinking.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Queen of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 13,
        keywords: &["independence", "clear boundaries", "perception", "honesty", "intelligence"],
        upright: "Clear perception cuts through illusion. Honest communication serves truth. Independence is your strength. Set clear boundaries with compassion.",
        reversed: "Coldness, cruelty, or cutting words. Judgment without empathy. Deception or being deceived. Overly emotional decisions.",
        description: "The Queen of Swords sits on her throne, sword raised in one hand, the other extended in reception, head turned slightly toward the sky. Her throne is decorated with cherubs and butterflies, suggesting that even clear intellect connects to spirit and transformation. This queen embodies clear perception, honest communication, and the strength that comes from knowing one's own mind. She has known sorrow—the clouds behind her suggest past grief—but has integrated it into wisdom. She speaks truth without cruelty and judges with clarity rather than coldness.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "King of Swords",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Swords),
        number: 14,
        keywords: &["mental clarity", "intellectual power", "authority", "truth", "discipline"],
        upright: "Lead with intellectual authority and truth. Clear thinking brings success. Justice and fairness guide decisions. Discipline of mind creates power.",
        reversed: "Tyranny, manipulation, or cruel authority. Judgment without mercy. Deceptive intellect. Ruthlessness masked as logic.",
        description: "The King of Swords sits on his throne, facing forward, sword raised in his right hand, the hand of action. His throne is decorated with butterflies and crescent moons, suggesting transformation and the connection between intellect and intuition. This king embodies mastery of the mental realm—clear thinking, fair judgment, and the authority that comes from wisdom. He leads through truth rather than force, through clarity rather than manipulation. The King of Swords reminds us that true intellectual power serves justice and truth.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    // ===== PENTACLES (Earth) =====
    Card {
        name: "Ace of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 1,
        keywords: &["manifestation", "prosperity", "opportunity", "abundance", "new venture"],
        upright: "A new opportunity for prosperity emerges. Seeds of abundance are planted. Manifestation is possible. The material world offers gifts.",
        reversed: "Missed opportunity, lack of planning, or financial loss. Seeds fail to take root. Material concerns block progress. False promise.",
        description: "A hand emerges from a cloud offering a pentacle, above a garden path leading through an archway to mountains beyond. This is the pure potential of earth—manifestation, prosperity, and material opportunity. Like all Aces, it represents a gift, but one that requires practical action to develop. The garden suggests that abundance grows through care and cultivation. The archway promises that this opportunity leads to greater achievements. The Ace of Pentacles speaks to the possibility of turning dreams into tangible reality.",
        element: None,
        astrology: Some("Taurus, Virgo, Capricorn"),
        numerology: Some("1 — new material beginning, seed of prosperity"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Two of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 2,
        keywords: &["balance", "adaptability", "time management", "priorities", "flexibility"],
        upright: "Balance competing priorities with flexibility. Adapt to changing circumstances. Juggle responsibilities with grace. Stay nimble.",
        reversed: "Overwhelm, poor time management, or dropping the ball. Imbalance creates stress. Too many commitments. Chaos from poor planning.",
        description: "A figure dances while juggling two pentacles, an infinity symbol connecting them, ships riding waves in the background. This is the card of balance and adaptability—the ability to manage multiple priorities while remaining flexible. The figure dances rather than struggles, suggesting that balance can be joyful rather than stressful. The ships on rough seas remind us that circumstances change and we must adapt. This card speaks to the art of juggling responsibilities, of staying flexible in the face of changing demands, and of finding rhythm in complexity.",
        element: None,
        astrology: Some("Jupiter in Capricorn"),
        numerology: Some("2 — balance, choice, adaptability"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Three of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 3,
        keywords: &["collaboration", "learning", "implementation", "teamwork", "skill"],
        upright: "Collaboration brings success. Your skills are recognized and valued. Teamwork achieves what individual effort cannot. Mastery through practice.",
        reversed: "Lack of teamwork, poor craftsmanship, or unappreciated skills. Working alone without support. Mediocrity. Miscommunication in collaboration.",
        description: "A craftsman works on a cathedral while two others consult plans, three pentacles adorning the archway above. This is the card of skilled work and collaboration—the recognition that great achievements require both individual mastery and teamwork. The craftsman is not working alone but as part of a greater vision. This card speaks to the value of expertise, the importance of collaboration, and the satisfaction of contributing one's skills to something larger than oneself. Success comes through both competence and cooperation.",
        element: None,
        astrology: Some("Mars in Capricorn"),
        numerology: Some("3 — creativity, collaboration, skill"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Four of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 4,
        keywords: &["security", "conservation", "frugality", "possessiveness", "control"],
        upright: "Protect what you have built. Financial security brings peace of mind. Save for the future. Establish solid foundations.",
        reversed: "Greed, materialism, or stinginess. Fear of loss prevents generosity. Holding on too tight. Insecurity despite having enough.",
        description: "A figure sits clutching four pentacles—one on their head, one in their arms, two under their feet—while a city sits behind them. This is the card of material security and its shadow side of possessiveness. The figure has achieved stability but at what cost? The posture suggests fear as much as security, a clinging to resources that may prevent growth. This card asks us to examine our relationship with material things: Are we building security or feeding fear? True abundance includes the freedom to share.",
        element: None,
        astrology: Some("Sun in Capricorn"),
        numerology: Some("4 — stability, security, foundation"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Five of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 5,
        keywords: &["hardship", "loss", "isolation", "worry", "financial struggle"],
        upright: "Material hardship tests your resilience. Help may be closer than it appears. Focus on spiritual wealth when material is lacking. This too shall pass.",
        reversed: "Recovery from hardship, finding help, or spiritual growth through difficulty. End of financial struggle. Community support appears. Hope returns.",
        description: "Two figures walk through snow past a stained glass window showing five pentacles, suggesting a church they do not enter. This is the card of material hardship, of feeling left out in the cold, of financial or physical struggle. Yet the warm light in the window suggests that help is available if sought—the figures are passing by resources that could aid them. This card acknowledges real difficulty while reminding us that we are never as alone as we feel, that community and spirit can sustain us even when material circumstances are challenging.",
        element: None,
        astrology: Some("Mercury in Taurus"),
        numerology: Some("5 — hardship, loss, challenge"),
        yes_or_no: YesOrNo::No,
    },
    Card {
        name: "Six of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 6,
        keywords: &["generosity", "charity", "sharing", "prosperity", "balance"],
        upright: "Give and receive with grace. Generosity flows in both directions. Share your abundance. Balance in giving and receiving.",
        reversed: "Strings attached to gifts, inequality, or selfishness. Unfair exchanges. Giving for show rather than love. Dependence rather than empowerment.",
        description: "A merchant figure distributes coins to two petitioners while holding a scale, six pentacles arranged above. This is the card of generosity and the balance of giving and receiving. The figure has abundance and shares it, but the scale suggests that this exchange should be fair and balanced. This card speaks to the flow of resources, the karmic balance of generosity, and the dignity of both giving and receiving. True charity empowers rather than creates dependence, and true prosperity is measured by what flows through us, not what we hoard.",
        element: None,
        astrology: Some("Moon in Taurus"),
        numerology: Some("6 — harmony, generosity, balance"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Seven of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 7,
        keywords: &["assessment", "patience", "investment", "long-term view", "reward"],
        upright: "Pause to assess your progress. Patience brings rewards. Your investments are growing—wait for harvest. Long-term thinking pays off.",
        reversed: "Impatience, lack of reward, or failed investments. Giving up too soon. Poor planning yields poor results. Delayed gratification becomes never.",
        description: "A figure leans on a staff, contemplating seven pentacles growing on a bush, a expression of patient assessment. This is the card of the long view, of investments made and now maturing, of the pause between effort and harvest. The figure is not working but observing, evaluating whether the growth justifies continued investment. This card speaks to the necessity of patience, of allowing time for efforts to bear fruit, and of the wisdom to assess whether we are investing our energy wisely.",
        element: None,
        astrology: Some("Saturn in Taurus"),
        numerology: Some("7 — assessment, patience, waiting"),
        yes_or_no: YesOrNo::Maybe,
    },
    Card {
        name: "Eight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 8,
        keywords: &["apprenticeship", "skill development", "diligence", "craftsmanship", "focus"],
        upright: "Dedication to mastery brings success. Focus on skill development. Diligent work yields results. The apprentice becomes the master.",
        reversed: "Lack of focus, perfectionism, or self-doubt. Boredom with work. Cutting corners. Unrecognized efforts. Burnout from overwork.",
        description: "A craftsman works diligently at his bench, focused on carving a pentacle while seven others hang completed on the wall. This is the card of dedicated work and skill development—the apprentice laboring toward mastery. The figure is absorbed in the task, not dreaming of the future but present with the work itself. This card speaks to the value of diligence, the satisfaction of craftsmanship, and the understanding that mastery comes through consistent effort over time. Success is built one pentacle at a time.",
        element: None,
        astrology: Some("Sun in Virgo"),
        numerology: Some("8 — work, mastery, diligence"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Nine of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 9,
        keywords: &["abundance", "luxury", "self-sufficiency", "refinement", "enjoyment"],
        upright: "Enjoy the fruits of your labor. Self-sufficiency brings freedom. Abundance surrounds you. Refinement and grace in prosperity.",
        reversed: "Overindulgence, financial dependence, or superficiality. Loneliness despite material comfort. Working without enjoying. False appearances.",
        description: "A graceful figure stands in a lush garden, a falcon on their gloved hand, nine pentacles arranged on the vine-covered wall. This is the card of accomplished abundance, of enjoying the fruits of labor without the need to prove anything. The figure is self-sufficient and at peace, surrounded by beauty they have cultivated. The falcon suggests both freedom and discipline—the bird could fly away but returns. This card speaks to the pleasure of material success when it serves rather than defines us.",
        element: None,
        astrology: Some("Venus in Virgo"),
        numerology: Some("9 — fulfillment, abundance, enjoyment"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Ten of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 10,
        keywords: &["legacy", "inheritance", "family", "long-term success", "established wealth"],
        upright: "Long-term success and family legacy. Generational abundance. Established security. The fruits of a life well-lived.",
        reversed: "Family conflict, financial failure, or loss of legacy. Short-term thinking. Material success without fulfillment. Breakdown of tradition.",
        description: "An elder sits with family in front of an archway adorned with ten pentacles, a prosperous estate visible beyond. This is the card of legacy and generational wealth, of the abundance that comes from long-term thinking and family bonds. The scene suggests not just material prosperity but the continuity of lineage, the passing of wisdom and resources from one generation to the next. This card speaks to the kind of success that outlives the individual, the establishment of security that benefits many.",
        element: None,
        astrology: Some("Mercury in Virgo"),
        numerology: Some("10 — completion, legacy, established success"),
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Page of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 11,
        keywords: &["ambition", "opportunity", "study", "manifestation", "new venture"],
        upright: "A new opportunity for material growth arrives. Ambition meets practical planning. Study and preparation serve your goals. Plant seeds of prosperity.",
        reversed: "Lack of progress, missed opportunity, or unrealistic ambitions. Procrastination. Study without application. Materialism without purpose.",
        description: "A young figure stands in a field, gazing intently at a pentacle they hold, trees and mountains in the background. This is the student of the material world, the one who approaches prosperity with curiosity and dedication. The Page of Pentacles represents new opportunities for growth, the beginning of practical ventures, and the ambition to build something lasting. The landscape suggests that this potential requires cultivation, but the focus on the pentacle indicates readiness to do the work.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Knight of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 12,
        keywords: &["diligence", "reliability", "responsibility", "stability", "methodical"],
        upright: "Steady progress brings results. Be reliable and methodical. Responsibility is your strength. Build foundations that last.",
        reversed: "Stagnation, boredom, or stubborn resistance to change. Moving too slowly. Over-caution prevents progress. Stuck in routine.",
        description: "A knight sits firmly on a stationary horse, holding a pentacle, planted fields behind them. This is the most steady and reliable of the knights—the one who approaches goals with methodical determination rather than haste. The Knight of Pentacles is not flashy but effective, building lasting results through consistent effort. The card brings the energy of responsibility and diligence, but also warns against becoming so focused on the method that progress stalls.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "Queen of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 13,
        keywords: &["nurturing", "practicality", "abundance", "comfort", "resourcefulness"],
        upright: "Nurture abundance in practical ways. Create comfort and security for yourself and others. Resourcefulness solves problems. Generous and grounded.",
        reversed: "Over-dependence on comfort, materialism, or neglect of self-care. Smothering rather than nurturing. Insecurity masked as generosity. Work without rest.",
        description: "The Queen of Pentacles sits on a throne in a garden, holding a pentacle, a rabbit at her feet suggesting fertility. This queen embodies the nurturing aspect of material abundance—she creates comfort, solves practical problems, and cares for others through tangible support. She is generous but grounded, luxurious but practical. The garden suggests that she cultivates prosperity rather than merely consuming it. This card speaks to the ability to create security and comfort through practical wisdom and caring attention.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
    Card {
        name: "King of Pentacles",
        arcana: ArcanaType::Minor,
        suit: Some(Suit::Pentacles),
        number: 14,
        keywords: &["abundance", "security", "discipline", "leadership", "mastery"],
        upright: "Lead with practical wisdom and abundance. Security comes through discipline. Master of material realm. Build lasting prosperity.",
        reversed: "Materialism, greed, or stubbornness. Wealth without generosity. Stubborn resistance to change. Corruption of success.",
        description: "The King of Pentacles sits on a throne adorned with bulls and grapes, holding a scepter and pentacle, a castle and abundant landscape behind him. This king embodies mastery of the material world—he has built security and abundance through discipline and wise leadership. He is generous but not foolish, prosperous but not defined by wealth. The card speaks to the ability to create and manage resources wisely, to lead through practical wisdom, and to enjoy abundance while remaining grounded in what truly matters.",
        element: None,
        astrology: None,
        numerology: None,
        yes_or_no: YesOrNo::Yes,
    },
];

/// Get a Minor Arcana card by suit and number
#[allow(dead_code)]
pub fn get_by_suit_and_number(suit: Suit, number: u8) -> Option<&'static Card> {
    MINOR_ARCANA
        .iter()
        .find(|c| c.suit == Some(suit) && c.number == number)
}

/// Get all cards of a specific suit
#[allow(dead_code)]
pub fn get_by_suit(suit: Suit) -> impl Iterator<Item = &'static Card> {
    MINOR_ARCANA.iter().filter(move |c| c.suit == Some(suit))
}

/// Get a Minor Arcana card by name
#[allow(dead_code)]
pub fn get_by_name(name: &str) -> Option<&'static Card> {
    let name_lower = name.to_lowercase();
    MINOR_ARCANA
        .iter()
        .find(|c| c.name.to_lowercase() == name_lower)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_minor_arcana_count() {
        assert_eq!(MINOR_ARCANA.len(), 56);
    }

    #[test]
    fn test_cards_per_suit() {
        assert_eq!(get_by_suit(Suit::Wands).count(), 14);
        assert_eq!(get_by_suit(Suit::Cups).count(), 14);
        assert_eq!(get_by_suit(Suit::Swords).count(), 14);
        assert_eq!(get_by_suit(Suit::Pentacles).count(), 14);
    }

    #[test]
    fn test_get_by_suit_and_number() {
        let ace = get_by_suit_and_number(Suit::Wands, 1).unwrap();
        assert_eq!(ace.name, "Ace of Wands");

        let king = get_by_suit_and_number(Suit::Cups, 14).unwrap();
        assert_eq!(king.name, "King of Cups");
    }

    #[test]
    fn test_get_by_name() {
        assert_eq!(get_by_name("Ace of Wands").unwrap().number, 1);
        assert_eq!(get_by_name("king of pentacles").unwrap().number, 14);
        assert!(get_by_name("Not a Card").is_none());
    }
}
